# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Habemus blog
site_title: Habemus
site_url: http://starter-projects.habemus.website/
dashboard_url: http://habemus.io/dashboard
email: hello@habem.us
description: A Habemus é uma plataforma de desenvolvimento web para a geração maker
# baseurl: "http://blog.habemus.website" # the subpath of your site, e.g. /blog
url: http://starter-projects.habemus.website # the base hostname & protocol for your site
twitter_username: "habemus_web"
github_username:  "habemus"

# Build settings
markdown: redcarpet
# lsi: true

# highlights
highlights:
  - parallax-scroll
  - squares-grid

permalink: /:year/:month/:day/:title.html