# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Habemus Starter Projects
site_title: Habemus
habemus:
  home_url: https://habemus.io
  dashboard_url: https://habemus.io/dashboard
email: hello@habem.us
# description: Projetos base Habemus - estrutura básica de arquivos e alguns componentes já integrados. São ótimos pontos de partida para começar seu website.
# baseurl: "http://blog.habemus.website" # the subpath of your site, e.g. /blog
# url: https://habemus.io/starter-projects # the base hostname & protocol for your site
twitter_username: "habemus_web"
github_username:  "habemus"

# Build settings
markdown: redcarpet
# lsi: true

permalink: /project/:slug.html
